name: Destroy Infrastructure

on:
  workflow_dispatch: # This allows manual triggering of the workflow from the GitHub Actions tab

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    # Log in to Azure using service principal credentials stored in GitHub Secrets
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Run a simple Azure CLI command to verify login
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    # Checkout the repository to access code and configuration files
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.11.3

    # Initialize Terraform configuration
    - name: Terraform Init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform init
      working-directory: ./terraform

    # Destory Infrastructure
    - name: Terraform Destroy
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform destroy --auto-approve
      working-directory: ./terraform

    # Clean up A record
    - name: Clean up A record
      run: |
        chmod +x cleanup.sh
        ./cleanup.sh
      working-directory: ./terraform/bash_scripts
